# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'msbuild  **/.eShopOnWeb.sln'
- task: dependency-check-build-task@6
  inputs:
    projectName: 'eShopOnWeb'
    scanPath: '.'
    format: 'HTML'